version: '3.5'
services:
  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kotlin
      POSTGRES_PASSWORD: kotlin
      POSTGRES_DB: restful-api